### ISSUE TITLE
Question about ODE likelihood

### ISSUE THREAD

**Issue by homerjed** [gle-bellier/discrete-fm#2]
Hi Georges

Thanks for this very nice implementation. 

I'm hoping to use this alongside a continuous FM model but ideally would need the use of an ODE formulation for the 'log-likelihood' - at first glance of the paper and your nice code - it seems this might not be possible. By 'log-likelihood' I mean calculating e.g. p(x) for an inference context.

Is this true? I've been using a Variational Diffusion Model for modelling discrete uint8 images which works nicely but FM is much faster!

Cheers
Jed

**Comment by lebellig** [comment]
Hi, 
Thank you for your feedback! To the best of my knowledge, we can't compute the likelihood with discrete flow matching. Despite the (continuous) flow matching using deterministic sampling via ODE (then allowing the computing of the likelihood), the sampling in the case of discrete flow matching is stochastic (eq 12 in the article):

$$X^i_{t+h} \sim \delta_{X^i_t}(\cdot) + h u_t^i(\cdot,X_t)$$ 

At each sampling step, we are updating the probability distribution and sampling a new $X$.

Best regards, 
Georges
